# Python Para Analise de Dados - Numpy

In [1]:
# Importando a Bibliotecas
import numpy as np
import pandas as pd

In [2]:
# Criando um array de 1 dimensão

one_dim = np.array([1, 2, 3, 4, 5])
one_dim

array([1, 2, 3, 4, 5])

In [3]:
# tipo

type(one_dim)

numpy.ndarray

In [4]:
# Imprimindo o Array

print(one_dim)

[1 2 3 4 5]


In [5]:
# Criando um array de 2 dimensoes

two_dim = np.array([(1, 2, 3), (4, 5, 6)])
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Imprimindo o array

print(two_dim)

[[1 2 3]
 [4 5 6]]


In [7]:
# Cria um array de numeros aleatorios
# Um array de 5 linhas e duas dimensoes

np.random.random((5, 2))

array([[0.54769405, 0.32746292],
       [0.92107542, 0.48152433],
       [0.7321096 , 0.45169282],
       [0.35379054, 0.73009284],
       [0.56016706, 0.05401403]])

In [8]:
# Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5

np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [9]:
# Cria um array linear de 0 e 2 de no maximo 9 elementos

np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
# Cria um array de valores zero
# Cria um array com 3 linhas e 4 dimensoes

np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Numpy Arrays Vs Listas

- Arrays Numpy permitem fazermos operações em **arrays inteiros** de forma rápida.
- Listas não permitem operações em todos os elementos da lista.
- Para operações em todos os elementos é preciso interar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos
- Arrays Numpy considera todos os elementos de tipos distintos como strings

In [ ]:
# Criando uma lista em Python

lista = [1, 2, 3]
lista

In [ ]:
# Multiplicar valores da lista por 2

lista * 2

In [ ]:
# Transforme a variavel lista em um array numpy

lista = np.array(lista)
lista

In [ ]:
# Multiplicando cada elemento por 2

lista * 2

In [ ]:
# Calcular IMC de pessoas

pesos = [67, 81, 120, 90]
altura = [1.68, 1.70, 1.74, 1.86]

In [ ]:
# Faz o calculo usando lista

pesos / altura ** 2 # Dara erro pois listas nao sao iteraveis, para isso deverei usa o for

In [ ]:
# Transformando isso em array numpy

pesos = np.array(pesos)
altura = np.array(altura)

In [ ]:
# Imprime o calculo de cada valor

pesos / altura ** 2

In [ ]:
# Array Numpy armazena elementos como strings quando estes não são inteiros ou float

a = np.array([1, 2, 'casa', True])
a

In [ ]:
a * 2

# Metodos e Atributos Uteis

In [ ]:
# Metodos e Atributos tecle tab
'''two_dim.'''

In [ ]:
two_dim

In [ ]:
# Retorna a forma do array no formato linhas e colunas

two_dim.shape

In [ ]:
# Retorna a quantidade de dimensoes

two_dim.ndim

In [ ]:
# Valor maximo do array

two_dim.max()

In [ ]:
# Valor Minimo do array

two_dim.min()

In [ ]:
# Valor Medio do array

two_dim.mean()

In [ ]:
# Imprimindo o desvio padrao

two_dim.std()

In [ ]:
two_dim

In [ ]:
# Tipo

two_dim.dtype

In [ ]:
# size

two_dim.size

In [ ]:
# Mostra a quantidade

two_dim.itemsize

In [ ]:
# Somando todos os elemntos do array

two_dim.sum()

# Transformando Array

In [ ]:
two_dim

In [ ]:
# Gera a transporta da matriz (linha - coluna)

two_dim.T

In [ ]:
# Transforma em uma matriz de uma linha
# E Muito comum em bibliotecas como scikit-learn e keras

two_dim.reshape(-1)

In [ ]:
# Novo array

tree = np.random.random((5, 3))
tree

In [ ]:
tree.shape

In [ ]:
# Transforma em uma matriz com 3 linhas e 5 colunas

tree.reshape(3, 5)

In [ ]:
tree.reshape(-1)

In [ ]:
t = tree.reshape(1, 15)
t

In [ ]:
two_dim

In [ ]:
# Adicionando elementos a um array

two_dim = np.insert(two_dim, 0, 10)
two_dim

In [ ]:
# Apagando o elemento da primeira posição do array

two_dim = np.delete(two_dim,[0])
two_dim

In [ ]:
# Gerando um arquivo .txt a partir de um array

np.savetxt('dataset_array.txt', two_dim, delimiter=',')

# Parte II - Acessand Dimensoes no Array

In [ ]:
# Importando o Numpy

import numpy as np
import pandas as pd

In [ ]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha,coluna

my_array = np.random.random([10, 2])
my_array

In [ ]:
# Imprimindo o Primeiro elemento (1 linha)

my_array[0]

In [ ]:
# Imprimindo o primeiro elemento da coluna 0 (1 coluna)

my_array[0][0]

In [ ]:
# Primeiro elemento da coluna 1

my_array[0][1]

In [ ]:
# Segundo elemento da coluna 1

my_array[1][1]

In [ ]:
# Segundo elemento da coluna escrito com virgula.
# O primeiro valor especifica a linha e o segundo valor especifica a coluna.

my_array[1,1]

In [ ]:
# Imprimindo até 3 valores da coluna 1

my_array[:3, 1]

In [ ]:
# Imprime todas as linhas da coluna 2 * 10

my_array[:,1] * 10

In [ ]:
# Comparação retorna indices

my_array > 0.50

In [ ]:
# Acessando valores por índices

my_array[my_array > 0.50]

## Carregar Arrays Numpy a Partir de arquivos de texto

In [ ]:
# Lendo um arquivo do tipo .txt

dataset = np.loadtxt('dataset_array.txt', delimiter=',')
dataset

In [ ]:
dataset.shape